fix: request ACL for ACO [#576]
ytsaurus/ytsaurus-ui pull request #574
Opened 2024-05-23 11:01 UTC by vitshev

https://nda.ya.ru/t/x52D79jM767p6v
    
https://github.com/ytsaurus/ytsaurus-ui/issues/576

2024-05-27 13:27 UTC, SimbiozizV submitted a review, later dismissed

2024-05-27 13:39 UTC, ma-efremoff requested changes
please do not merge the PR

2024-05-31 13:38 UTC, ma-efremoff commented on packages/ui/src/shared/utils/index.ts
> +    console.log('makeRegexpFromSettings', value);
Please remove `console.log(...)`

2024-05-31 13:38 UTC, ma-efremoff commented on packages/ui/src/ui/utils/acl/index.ts
> +            ACCESS_CONTROL_OBJECT_ANY_REGEXP.test(path)
`ACCESS_CONTROL_OBJECT_ANY_REGEXP?.test(path)`

2024-05-31 13:38 UTC, ma-efremoff commented on packages/ui/src/ui/utils/acl/index.ts
> +const ACCESS_CONTROL_OBJECT_ANY_REGEXP =
```ts
const ACCESS_CONTROL_OBJECT_ANY_REGEXP = makeRegexpFromSettings(uiSettings.reUseEffectiveAclForPath);
```

2024-05-31 13:38 UTC, ma-efremoff commented on packages/ui/src/ui/utils/acl/acl-api.ts
> -    }
please bring back the if-expression

2024-05-31 13:38 UTC, ma-efremoff commented on packages/ui/src/server/configs/common.ts
> +        reUseEffectiveAclForPath: '//sys/access_control_object_namespaces[^/+]{0,}',
I don't think we need default value for the option here (or in local.ts). But it is a good idea to have corresponding e2e to be sure the functionality works propertly.

2024-05-31 14:16 UTC, ma-efremoff commented on packages/ui/src/ui/constants/acl.ts
> +    [IdmObjectType.UI_EFFECTIVE_ACL]: {
I think it is enough to check that some acl are rendered and there are no buttons to request/manage them.

2024-05-31 14:19 UTC, ma-efremoff commented on packages/ui/src/ui/utils/acl/index.ts
> +const ACCESS_CONTROL_OBJECT_ANY_REGEXP =
According to current implementation of `makeRegexpFromSettings` you should get `undefined`

2024-05-31 14:20 UTC, ma-efremoff commented on packages/ui/src/ui/utils/acl/index.ts
> +const ACCESS_CONTROL_OBJECT_ANY_REGEXP =
Oh, sorry, I am wrong. Can we rewrite `makeRegexpFromSettings` to have `undefined` for the case?

2024-05-31 14:25 UTC, ma-efremoff commented on packages/ui/src/shared/utils/index.ts
> +        return new RegExp(value!);
it is better to return undefined when `Boolean(value) === false`

2024-06-03 10:17 UTC, ma-efremoff commented on packages/ui/src/server/configs/e2e/local.ts
> +        reUseEffectiveAclForPath: '//sys/access_control_object_namespaces[^/+]{0,}',
Editing of the file is a good reason to edit some files from `packages/UI/tests`.

2024-06-03 14:58 UTC, ma-efremoff commented on packages/ui/tests/e2e/pages/aco.spec.ts
> +    await acoPage.open();
Do we really need secondary open-call?

2024-06-03 16:05 UTC, ma-efremoff commented on packages/ui/tests/e2e/pages/aco.spec.ts
> +    await expect(page.getByText('Request permissions')).toBeHidden();
We need to wait content of ACL tab before check visibility of the button.

2024-06-06 14:05 UTC, ma-efremoff approved these changes

2024-06-06 14:11 UTC, merged